[package]
name = "blink"
version = "0.1.0"
authors = ["Michael Daffin <michael@daffin.io>"]
build = "build.rs"

[dependencies]
rust-libcore = "*"

[profile.dev]
opt-level = 0
debug = true
panic = "abort"

[profile.release]
opt-level = 2
debug = false
panic = "abort"
